### ISSUE TITLE
Check requirements.txt

### ISSUE THREAD

**Issue by tagozzo** [sabiharustam/Voltcycle#5]
Just let me know if the requirements I listed end up being the minimal we need for our package to function properly! Our functions run fine, but I want to make sure I have all the necessary things for Dash.

**Comment by jrodguez** [comment]
@tagozzo Chowdhury and I both created a virtual environment and pip installed, but got this error when we tried to run the dash file:

```ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.```

I'm not sure what it means exactly, but we are looking into it.

**Comment by tagozzo** [comment]
Okay, thank you! I use Windows, so let me know what you find out!

**Comment by cmashraf** [comment]
Probably the problem is with macOS. Upon installing the environment using the requirement.txt file, I did the following

- since we are pip installing, there should be a directory at root called ~/.matplotlib.
Create a file ~/.matplotlib/matplotlibrc there and add the following code: backend: TkAgg

We can circumvent this issue by installing Matlab through conda

- conda create -n env_name python=3.7.1 matplotlib
- remove the matplotlib line from requirements.txt
- pip install -r requirements.txt

Also, the environment created by this requirements.txt file works fine with dash!!
